// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBoRnJztByyTFMKamTiD2O56vffwT9Qxw',
    appId: '1:806112196065:web:e7f4c26ada752555bc0ea0',
    messagingSenderId: '806112196065',
    projectId: 'notifications-test-282d5',
    authDomain: 'notifications-test-282d5.firebaseapp.com',
    storageBucket: 'notifications-test-282d5.firebasestorage.app',
    measurementId: 'G-26VNFWSFJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhcJQzk7GYdQYCI42oZk3eKEEkX1wBjqM',
    appId: '1:806112196065:android:3677f068ba00611cbc0ea0',
    messagingSenderId: '806112196065',
    projectId: 'notifications-test-282d5',
    storageBucket: 'notifications-test-282d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT5AOoI1rhCrAgwzt_HylrDDS759J9IX8',
    appId: '1:806112196065:ios:23187f6154fb4d6ebc0ea0',
    messagingSenderId: '806112196065',
    projectId: 'notifications-test-282d5',
    storageBucket: 'notifications-test-282d5.firebasestorage.app',
    iosBundleId: 'com.example.notTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT5AOoI1rhCrAgwzt_HylrDDS759J9IX8',
    appId: '1:806112196065:ios:23187f6154fb4d6ebc0ea0',
    messagingSenderId: '806112196065',
    projectId: 'notifications-test-282d5',
    storageBucket: 'notifications-test-282d5.firebasestorage.app',
    iosBundleId: 'com.example.notTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBoRnJztByyTFMKamTiD2O56vffwT9Qxw',
    appId: '1:806112196065:web:5db6c648fb45e28ebc0ea0',
    messagingSenderId: '806112196065',
    projectId: 'notifications-test-282d5',
    authDomain: 'notifications-test-282d5.firebaseapp.com',
    storageBucket: 'notifications-test-282d5.firebasestorage.app',
    measurementId: 'G-7HJHLQMJDG',
  );
}
